
credentials:
  usernames:
    guilherme.gomes:
      email: guilherme.gomes@locaweb.com.br
      name: Guilherme Gomes
      password: $2b$12$Twr92H.AXtqa75Yqxg9jqu7NnjQCqQU4TvwzKRbgDcDm6jKyqbxCm # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com